version: "3.7"
services:
  db:
    image: postgres:9.4
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - database.env
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "WebsiteStatus:1:1"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - "zookeeper"
volumes:
   db-data: